import { getKeyFromMnemonic } from "arweave-mnemonic-keys";
import { NetworkType } from "@dojima-wallet/types/dist/lib/network";
import { ArweaveAccount } from "@dojima-wallet/account";
import Transaction from "arweave/node/lib/transaction";

export default class ArweaveChain extends ArweaveAccount {
  constructor(mnemonic: string, network: NetworkType) {
    super(mnemonic, network);
  }

  async getBalance(): Promise<number> {
    const pvtKey = await getKeyFromMnemonic(this._mnemonic);
    // console.log('Pvt key is : ' + pvtKey);
    const pubAddress = await this._arweave.wallets.jwkToAddress(pvtKey);
    // console.log('Pub Address is : ' + pubAddress);

    // Get balance
    let wnstBalance = await this._arweave.wallets.getBalance(pubAddress);
    // console.log("Winston balance is : ", wnstBalance);

    // Convert balance from Winston to Ar. (1 Ar = 10^12)
    const arBalance = this._arweave.ar.winstonToAr(wnstBalance);
    // console.log("Ar balance is : ", arBalance);

    return Number(arBalance);
  }

  // Create transaction based on user inputs
  async createTransaction(
    toAddress: string,
    amount: number
  ): Promise<Transaction> {
    const pvtKey = await getKeyFromMnemonic(this._mnemonic);
    // const pubAddress = await this._arweave.wallets.jwkToAddress(pvtKey);
    // console.log('Pub Address is : ' + pubAddress);

    // Create transaction
    const rawTx = await this._arweave.createTransaction(
      {
        target: toAddress, // Receiver address
        quantity: this._arweave.ar.arToWinston(amount.toString()), // Amount to transfer in Ar
      },
      pvtKey
    );

    return rawTx;
  }

  // Calculate gasFee required for transaction
  getGasFee(rawTx: Transaction) {
    // Gas fee generated by default during 'createTransaction'
    const gasFee = Number(rawTx.reward);
    return {
      slow: {
        fee: gasFee,
      },
      average: {
        fee: gasFee,
      },
      fast: {
        fee: gasFee,
      },
    };
  }

  // Sign and Send the transaction
  async signAndSend(rawTx: Transaction) {
    const pvtKey = await getKeyFromMnemonic(this._mnemonic);
    // const pubAddress = await this._arweave.wallets.jwkToAddress(pvtKey);

    // Sign transaction and retreive status
    await this._arweave.transactions.sign(rawTx, pvtKey);
    const status = await this._arweave.transactions.post(rawTx);
    await this._arweave.api.get("/mine");
    // console.log("transfer status", status);

    if (status.status == 200) {
      // console.log('Transaction Hash / Id is : ' + transaction.id);
      // Get status data using transaction hash / id
      // const statusData = await arweave.transactions.getStatus(rawTx.id);

      // console.log(JSON.stringify(statusData));

      return rawTx.id;
    } else {
      console.log(
        "Error in status: Posting the transaction into arweave transactions"
      );
    }
  }
}
