import { NetworkType } from "@dojima-wallet/types/dist/lib/network";
import { Client } from "@xchainjs/xchain-bitcoin";
import { AssetBTC, baseAmount } from "@xchainjs/xchain-util";
import { BigNumber } from "bignumber.js";
import { BitcoinClient } from "@dojima-wallet/connection";

export default class BitcoinChain extends BitcoinClient {
  constructor(mnemonic: string, network: NetworkType) {
    super(mnemonic, network);
  }

  // Retrieve balance of the user
  async getBalance(client: Client) {
    const balanceObject = await client.getBalance(client.getAddress());
    const balance =
      balanceObject[0].amount.amount().toNumber() /
      Math.pow(10, balanceObject[0].amount.decimal);
    return balance;
  }

  // Get gasFeeRate for transaction
  // getFeeRates() returns gas fee generated by
  // 'thorchain' else 'sochain'
  // Note: For 'fast' transaction we are making use of gasFee same as 'average'
  async getGasFee(client: Client) {
    const feeRates = await client.getFeeRates();
    // console.log('Rates : ', feeRates);
    return {
      slow: {
        fee: feeRates.average,
      },
      average: {
        fee: feeRates.fast,
      },
      fast: {
        fee: feeRates.fast,
      },
    };
  }

  // Transfer tokens to the receiver
  async createTransactionAndSend(
    toAddress: string,
    amount: number,
    client: Client,
    feeRate?: number
  ) {
    // Convert amount to BigNumber
    const toAmount = new BigNumber(amount * Math.pow(10, 8));
    // console.log('To amount : ', toAmount.toNumber().toFixed(2));

    // BaseAmount value
    const bsAmount = baseAmount(toAmount, 8);
    // console.log('Base amount : ', bsAmount.amount());

    // Transfer amount to recipient
    const transactionHash = await client.transfer({
      walletIndex: 0,
      asset: AssetBTC,
      recipient: toAddress,
      amount: bsAmount,
      memo: "SWAP:BTC.BTC",
      feeRate: feeRate ? feeRate : 1, // 1 is for testing purpose
    });
    // console.log('Transaction id : ', transactionHash);
    return transactionHash;

    // Get transaction details using transaction hash.
    // Display details only for confirmed transactions else status error
    // try {
    //     const transactionDetails = await this._client.getTransactionData(transactionHash);
    //     console.log('Transaction Details : ', transactionDetails);
    //     return {
    //         transactionDetails,
    //         transactionHash
    //     }
    // } catch (error) {
    //     console.log('Error is : ', error);
    // }
  }
}
